### PR TITLE
check filter instead of name

### PR DESCRIPTION
**Pull request by jeffrey-slentz-algolia**
## Objective
What: checks defined filter instead
Why: lets user change link in headerConfig.js from "All"
How: check filter is empty or not
Usage: n/a

## Type

- [X] Bug Fix
- [ ] New Feature
- [ ] Performance Tweaks
- [ ] Style Tweaks
- [ ] Code Refactoring
- [ ] Documentation
- [ ] Tests

## Tested

Outline the approach you've taken to test the change

Changed first link's name in headerConfig.js to 'All Products' and clicked

## Documented

- [ ] Have you documented in changed file using comments
- [ ] Have you added instructions to the README if needed?

### CODE REVIEW

**Review by matthew1809 — APPROVED** [review]
GG!

**Review by matthew1809 — COMMENTED** [review]
Hey qq, do context driven links still work with the change you made @jeffrey-slentz-algolia?

**Comment by jeffrey-slentz-algolia** [comment]
Great catch! I refactored the if statements around

**Review by matthew1809 — APPROVED** [review]
GG!

**Pull request merged**
