### PR TITLE
Feat/predict pdp discount

### PR DESCRIPTION
**Pull request by matthew1809**
## Objective
What: Add a dynamic discount for FBT if recommendations are over buying power or if current cart total is over buying power

Why: User likely needs an incentive to buy if the above conditions are true

How: Predict zone to show the discount message and predict hook to get buying power to update the price

Usage: Search for "bag", click first result (5VA54H00I), look at FBT to see no discount, check logs to know why. Add something about 75 pounds to the cart, then look for that bag again. This time, show the discount message, check the logs to know why.

## Type
- [X] New Feature

## Tested
Localhost

## Translation
- [ ] Have you translated all your Paragraphs, ButtonsTitle,... with i18n functionality?

## Documented
- [ ] Have you documented in changed file using comments
- [ ] Have you added instructions to the README if needed?

### CODE REVIEW

**Review by VirAlex — COMMENTED** [review]
It's really nice good job @matthew1809 but if there are not Related or not FBT, maybe I don't understand predict correctly but in this case I have the promo code but without any products
Screenshot 2022-10-20 at 09 02 57

**Comment by matthew1809** [comment]
> It's really nice good job @matthew1809 but if there are not Related or not FBT, maybe I don't understand predict correctly but in this case I have the promo code but without any products Screenshot 2022-10-20 at 09 02 57

Great catch! To test, please try it on the first result for "bag" and let me know what you see if you cart is empty, vs if you have more than 80 in your cart already

**Review by HugoWith — APPROVED** [review]
Hey @matthew1809 , 

Thanks a lot well done. I Have a few questions to get how everything is working if you don't mind me asking :) 

#1 
How do we retrieve every params coming from Predict API. I couldn't find anything on the app : YCWMGWBZQ0 
(i.e picture)
Screenshot 2022-10-20 at 13 55 39


#2 
Why this component is unused ? 
Screenshot 2022-10-20 at 13 58 24

**Comment by matthew1809** [comment]
https://share.vidyard.com/watch/ykdL4ZJtdPRdUgkMU8sqX9

**Pull request merged**
