### PR TITLE
Cu 32q93wp add a btn on fbt pdp page to add every product at once 

### PR DESCRIPTION
**Pull request by VirAlex**
## Objective
What: Add the possibility to add all FBT articles
Why: because it's an expected
How: Reused the function add to cart

## Type

- [x] New Feature

## Tested

✅

## Translation

- [x] Have you translated all your Paragraphs, ButtonsTitle,... with i18n functionality?

## Documented

- [x] Have you documented in changed file using comments

screencapture-127-0-0-1-5173-search-product-BU112M0AO-2022-10-13-16_34_52
screencapture-chrome-extension-fdpohaocaechififmbbbbbknoalclacl-capture-html-2022-10-13-16_35_07

### CODE REVIEW

**Comment by diegolarraz** [comment]
Task linked: [CU-32q93wp Add a btn on FBT (PDP page) to add every product at once](https://app.clickup.com/t/32q93wp)

**Review by diegolarraz — APPROVED** [review]
LGTM!!

**Comment by matthew1809** [comment]
Some small feedback, FBT should also show the original product on the left, look at the Magento screenshot you linked in the task, the original product is there, plus two more, and that's what you can add to the cart

I think personally it's worth doing a Figma design for this modal if you think it would help you design the UI aspect of it :)

**Comment by VirAlex** [comment]
> Some small feedback, FBT should also show the original product on the left, look at the Magento screenshot you linked in the task, the original product is there, plus two more, and that's what you can add to the cart
> 
> I think personally it's worth doing a Figma design for this modal if you think it would help you design the UI aspect of it :)

I didn't touch the design of the cards we talked about it this morning with @HugoWith and that was ou feedback to create only a button with a total value but if you decide to to the exact same thing as Magento NP I'll work on it next week

**Comment by HugoWith** [comment]
Closing for the moment. Will create a better experience. Saw that wit @VirAlex

**Pull request closed without merging**
