### PR TITLE
fluid font & banner fix on mobile

### PR DESCRIPTION
**Pull request by HugoWith**
## Objective
What: fluid font (banner home) & banner fix on mobile
Why: fix 
How: using clamp function (css)

## Type

- [x] Bug Fix
- [ ] New Feature
- [ ] Performance Tweaks
- [x] Style Tweaks
- [ ] Code Refactoring
- [ ] Documentation
- [ ] Tests

## Tested

https://share.getcloudapp.com/WnuDAyxb

## Documented

- [ ] Have you documented in changed file using comments
- [ ] Have you added instructions to the README if needed?

### CODE REVIEW

**Comment by diegolarraz** [comment]
Task linked: [CU-2rrhqr8 Responsiveness Banner](https://app.clickup.com/t/2rrhqr8)

**Review by matthew1809 — COMMENTED** [review]
Screenshot 2022-09-06 at 12 09 17
should button be hidden behind text? Is there a better place for it/should it exist?

**Comment by HugoWith** [comment]
> Screenshot 2022-09-06 at 12 09 17
> 
> should button be hidden behind text? Is there a better place for it/should it exist?

Hey @matthew1809 
This is the fix 👇

Screenshot 2022-09-06 at 12 14 25

**Comment by HugoWith** [comment]
> Task linked: [CU-2rrhqr8 Responsiveness Banner](https://app.clickup.com/t/2rrhqr8)

Hey @diegolarraz 
I linked it direclty from click up. Not sure if it's the right way to do it :

Screenshot 2022-09-06 at 12 17 15

**Comment by matthew1809** [comment]
> > Screenshot 2022-09-06 at 12 09 17
"383" src="https://user-images.githubusercontent.com/10894967/188608783-76da39bf-cc01-4d04-ba2d-671ba6d69101.png">
> > should button be hidden behind text? Is there a better place for it/should it exist?
> 
> Hey @matthew1809 This is the fix 👇
> 
> Screenshot 2022-09-06 at 12 14 25

Weird I'm on mobile view in desktop and don't see the adjustment

**Comment by HugoWith** [comment]
https://github.com/algolia/algolia-react-boilerplate/pull/363#issuecomment-1237960817

Hmmm this is weird could you pull again ? 😊

**Comment by HugoWith** [comment]
Screenshot 2022-09-06 at 12 34 16

It's working fine on the deploy preview 😊

cc @matthew1809

**Comment by matthew1809** [comment]
That's great to hear Hugo, must be an anomaly on my machine!

**Review by matthew1809 — APPROVED** [review]
GG!

**Pull request merged**
